/**
 * secretKekHelper.ts — shared test helper (PBI 25-25). NOT a test file.
 *
 * Installs an in-memory secret wrapping KEK behind the override seam,
 * standing in for IndexedDB (absent in unit environments). Without this,
 * fresh secret generation fails closed with ENCRYPTION_UNAVAILABLE.
 *
 * Call AFTER any real-crypto assignment in the file's setup: the KEK must be
 * generated by the same getWebCrypto() the production code resolves
 * (cross-realm CryptoKey instances are rejected by subtle). In files that
 * assign `global.crypto` inside beforeEach, call this last.
 */
import { webcrypto as nodeWebCrypto } from 'node:crypto';
import { getWebCrypto } from '../primitives.js';
import { setSecretKeyStorageOverride } from '../secretWrappingKey.js';

const ALGORITHM = { name: 'AES-GCM', length: 256 } as const;
const USAGES = ['encrypt', 'decrypt'] as const;

async function generateKek(): Promise<CryptoKey> {
  let ambient: unknown = null;
  try {
    // A stubbed `subtle.generateKey` returns undefined rather than a promise,
    // so the await has to be the thing that tolerates both shapes.
    ambient = await getWebCrypto().subtle.generateKey(ALGORITHM, false, [...USAGES]);
  } catch {
    ambient = null;
  }
  if (ambient) {
    return ambient as CryptoKey;
  }
  // Suites that swap `global.crypto` for a vi.fn() stub land here. Their
  // subtle.encrypt is a no-op too, so the envelope content is never inspected;
  // a real key from Node's implementation only needs to get the production
  // availability check past. Real-crypto suites take the branch above.
  return (await nodeWebCrypto.subtle.generateKey(ALGORITHM, false, [...USAGES])) as CryptoKey;
}

export async function installTestSecretKek(): Promise<void> {
  const kek = await generateKek();
  setSecretKeyStorageOverride({
    get: async () => kek,
    put: async () => {},
  });
}
