#!/usr/bin/env node

/**
 * Per-file cost report for the unit suite, gated against a checked-in budget.
 *
 * The suite is bound by per-file fixed cost, not by test count: 907 files each
 * pay a fork, an environment, the setup file and a transform. That makes the
 * file count — and any fixed sleep inside a file — the thing worth budgeting.
 *
 * Writes bench/reports/test-perf.md and fails when the measured totals exceed
 * bench/baselines/test-perf.budget.json. Run it before adding test files.
 *
 * What the JSON reporter can and cannot measure: `startTime`/`endTime` bracket
 * the test phase only, so the per-file numbers below exclude the environment,
 * transform, import and setup cost that the ADR puts at ~74% of the run. Wall
 * is the only figure that includes it, and wall is also what the suite is least
 * stable in, so the pass/fail decision is made on the machine-independent
 * metrics and wall is reported alongside. See the budget block at the bottom.
 *
 * See dev-docs/ADR/2026-09-26-test-suite-execution-time-contract.md
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const REPORT_DIR = join(ROOT, 'bench', 'reports');
const REPORT_PATH = join(REPORT_DIR, 'test-perf.md');
const BUDGET_PATH = join(ROOT, 'bench', 'baselines', 'test-perf.budget.json');

function percentile(sorted, p) {
  if (sorted.length === 0) return 0;
  return sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * p))];
}

const raw = join(REPORT_DIR, '.test-perf-raw.json');
mkdirSync(REPORT_DIR, { recursive: true });

const cores = os.availableParallelism();
// Sampled before the run on purpose. The suite saturates every core for its
// whole duration, so a reading taken afterwards is dominated by this run's own
// load and would report "busy" on an idle machine — which is how the gate came
// to never reach a verdict. ADR R5 asks for the load on both sides of the run.
const loadBefore = os.loadavg()[0];
const contendedBefore = loadBefore > cores;

const run = spawnSync('npx', ['vitest', 'run', '--reporter=json', `--outputFile=${raw}`], {
  cwd: ROOT,
  stdio: ['ignore', 'inherit', 'inherit'],
  shell: process.platform === 'win32',
});

if (run.status !== 0) {
  console.error('test-perf: vitest run failed; budget not evaluated');
  process.exit(run.status ?? 1);
}

const payload = JSON.parse(readFileSync(raw, 'utf8'));

const files = (payload.testResults ?? [])
  .map((entry) => {
    const assertions = entry.assertionResults ?? [];
    const assertionMs = assertions.reduce((sum, a) => sum + (a.duration ?? 0), 0);
    const start = entry.startTime ?? 0;
    const end = entry.endTime ?? 0;
    return {
      file: relative(ROOT, entry.name),
      // The reporter derives startTime/endTime from the individual test tasks
      // (min start, max start+duration), so this span is the test phase plus
      // inter-test gaps — NOT the file lifecycle. Measured: summed span 84.67ms
      // against summed assertion durations 84.07ms, a 0.6ms delta that
      // reproduces the ADR's full-suite figures (87.6s vs 87.0s). Environment,
      // transform, import and the shared setup file all fall outside it.
      ms: Math.max(0, end - start),
      assertionMs,
      tests: assertions.length,
      failed: assertions.filter((a) => a.status === 'failed').length,
      start,
      end,
    };
  })
  .sort((a, b) => b.ms - a.ms);

// The JSON reporter has no totalTime field; wall is the span from the earliest
// file start to the latest file end.
const wallMs = files.length > 0 ? Math.max(...files.map((f) => f.end)) - Math.min(...files.map((f) => f.start)) : 0;

const totalMs = files.reduce((s, f) => s + f.ms, 0);
const assertionTotalMs = files.reduce((s, f) => s + f.assertionMs, 0);
const sorted = files.map((f) => f.ms).sort((a, b) => a - b);
const top10Ms = files.slice(0, 10).reduce((s, f) => s + f.ms, 0);
const failures = (payload.numFailedTests ?? 0) + (payload.numFailedTestSuites ?? 0);

const measured = {
  files: files.length,
  tests: files.reduce((s, f) => s + f.tests, 0),
  totalMs: Math.round(totalMs),
  assertionTotalMs: Math.round(assertionTotalMs),
  p50Ms: Math.round(percentile(sorted, 0.5)),
  p95Ms: Math.round(percentile(sorted, 0.95)),
  top10Ms: Math.round(top10Ms),
  wallMs: Math.round(wallMs),
  failed: failures,
};

const rows = files
  .slice(0, 25)
  .map((f, i) => `| ${i + 1} | ${f.file} | ${f.tests} | ${f.ms} | ${f.assertionMs} |`)
  .join('\n');

const report = [
  '# Unit test per-file cost',
  '',
  'Generated by `npm run test:perf`. Budget: `bench/baselines/test-perf.budget.json`.',
  '',
  'Both time columns cover the TEST PHASE ONLY. The JSON reporter has no span',
  'that reaches a file lifecycle, so the per-file fixed cost the ADR puts at',
  '~74% of the run (environment, transform, import, the shared setup file) is',
  'NOT in any number here. That cost is held down by the file-count gate, which',
  'is the only machine-independent one; the time figures below are reported for',
  'a human to read and are not what fails the build.',
  '',
  '## Totals',
  '',
  `- files: ${measured.files}`,
  `- tests: ${measured.tests}`,
  `- wall: ${(measured.wallMs / 1000).toFixed(2)}s (advisory; includes fixed cost, but is machine-dependent)`,
  `- summed per-file test phase: ${(measured.totalMs / 1000).toFixed(2)}s`,
  `- summed assertion durations: ${(measured.assertionTotalMs / 1000).toFixed(2)}s`,
  `- p50 per file: ${measured.p50Ms}ms`,
  `- p95 per file: ${measured.p95Ms}ms`,
  `- top 10 files: ${(measured.top10Ms / 1000).toFixed(2)}s`,
  `- failed tests / suites: ${failures}`,
  '',
  '## Slowest files',
  '',
  '| # | file | tests | per file (ms) | tests only (ms) |',
  '|---|------|-------|----------------|-----------------|',
  rows,
  '',
].join('\n');

writeFileSync(REPORT_PATH, report);
console.log(`test-perf: wrote ${relative(ROOT, REPORT_PATH)}`);

if (failures > 0) {
  console.error('test-perf: the suite has failures; fix those before judging the budget');
  process.exit(1);
}

const budget = JSON.parse(readFileSync(BUDGET_PATH, 'utf8')).budget;
const budgetFileCount = budget.gates.fileCount;

// ADR R4: refuse to judge on a busy machine. The per-file times inflate 3-5x
// under contention, so comparing them to a budget here would fail a correct
// implementation — and the only remedy left would be raising the budget, which
// is the coping gradient R4 exists to prevent. The file-count gate below is
// machine-independent and is judged either way.
//
// Only the BEFORE sample decides. R5 asks for a before/after pair and to
// discard on a delta >= 1, but a suite that saturates every core for its whole
// duration always produces such a delta: measured on an idle machine here,
// load went 3.0 -> 14.3 across one run, so the literal rule discards every
// measurement and the gate never reaches a verdict — the same dead-gate failure
// R4 was written to fix. The after-sample is still read, because a machine that
// was already busy and stayed busy is worth reporting.
const loadAfter = os.loadavg()[0];
if (contendedBefore) {
  console.log(
    `test-perf: load average was ${loadBefore.toFixed(1)} over ${cores} cores before the run (${loadAfter.toFixed(1)} after) — machine is busy, budget not judged`
  );
  console.log('test-perf: per-file times inflate 3-5x under load; re-run on an idle machine');
  if (measured.files > budgetFileCount) {
    console.error(`test-perf: file count ${measured.files} exceeds ${budgetFileCount} regardless of load`);
    process.exit(1);
  }
  console.log(`  ok   file count (load-independent): ${measured.files} / ${budgetFileCount}`);
  process.exit(0);
}

// Only the file count fails the build. The time figures are calibrated on one
// 8-core laptop; a 4-vCPU CI runner at a pinned 3 workers has a different
// per-core speed, and `p95`/`top10` additionally absorb shared-VM scheduling
// noise. A routine runner difference would otherwise fail `validate`, and since
// `build` declares `needs: validate` it would block the build artifact too.
const gates = [['file count', measured.files, budget.gates.fileCount]];
const advisories = [
  ['total test phase', measured.totalMs, budget.reference.totalFileMs],
  ['p95 per file', measured.p95Ms, budget.reference.p95FileMs],
  ['top 10 files', measured.top10Ms, budget.reference.top10Ms],
];

let breached = false;
for (const [label, actual, limit] of gates) {
  const over = actual > limit;
  if (over) breached = true;
  const pct = limit > 0 ? ((actual / limit) * 100).toFixed(0) : 'n/a';
  console.log(`  ${over ? 'OVER ' : 'ok   '}${label}: ${Math.round(actual)} / ${limit} (${pct}%)  [gated]`);
}
for (const [label, actual, limit] of advisories) {
  const over = actual > limit;
  const pct = limit > 0 ? ((actual / limit) * 100).toFixed(0) : 'n/a';
  console.log(`  ${over ? 'over' : 'ok  '}${label}: ${Math.round(actual)} / ${limit} (${pct}%)  [advisory]`);
}

console.log(`  info  wall: ${(measured.wallMs / 1000).toFixed(1)}s over ${cores} cores (advisory, machine-dependent)`);
console.log('  info  per-file fixed cost is not measurable by the JSON reporter; file count stands in for it');

if (breached) {
  console.error('test-perf: budget exceeded. Either the suite grew, or the budget needs a deliberate raise.');
  process.exit(1);
}
console.log('test-perf: within budget');
